### ISSUE TITLE
#2 Decision making on tech-stacks

### ISSUE THREAD

**Issue by sjw2023** [sjw2023/go-play-ground#2]
# Objective
- Make decision what to use.
# TODO List
- [ ] Research front-end
- [ ] Research back-end
- [ ] Research database if needed
- [ ] Research the way to host website ( e.g, AWS, GOOGLE, Naver etc ... )
- [ ] CI/CD Tool chain

**Comment by sjw2023** [comment]
# Back-end
- Language : Go
- Framework : [Iris](https://www.iris-go.com/), [Gin](https://go.dev/doc/tutorial/web-service-gin), [Beego](https://github.com/beego/beego),[Echo](https://echo.labstack.com/), [Fiber](https://github.com/gofiber/fiber), [Revel](https://revel.github.io/)
